ignore:
  - "anuvikar/third_party/*" # ignoring catch, clipp and disjoint-set
  - "anuvikar/src/main.cpp"  # ignoring for only boilerplate 
  - "anuvikar/src/printJson.cpp" # ignoring for only printing boilerplate 
  - "anuvikar/include/printJson.hpp" # ignoring for only printing boilerplate 
  - "third_party/*" # ignoring catch, clipp and disjoint-set
  - "src/main.cpp"  # ignoring for only boilerplate 
  - "src/printJson.cpp" # ignoring for only printing boilerplate 
  - "include/printJson.hpp" # ignoring for only printing boilerplate
