name: anuvikar
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20.3
  - python=3.7.3
  - scikit-learn=1.0
  - scipy=1.7.1
  - hdbscan=0.8.27
  - umap-learn=0.5.1
  - numba=0.54.1
  - xmltodict>=0.12
  - seaborn=0.11.2
  - jupyter>=1.0.0
  - networkx=2.6.3
